name: Update Market Data & Deploy Site

permissions:
  contents: read
  pages: write
  id-token: write

on:
  schedule:
    - cron: '*/30 * * * *'  # تغییر از 5 دقیقه به 30 دقیقه
  workflow_dispatch:

jobs:
  process-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests upstash_redis

      - name: Run Price Scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          UPSTASH_URL: ${{ secrets.UPSTASH_URL }}
          UPSTASH_TOKEN: ${{ secrets.UPSTASH_TOKEN }}
          PF_GOLD_QTY: ${{ vars.PF_GOLD_QTY }}
          PF_GOLD_AVG: ${{ vars.PF_GOLD_AVG }}
          PF_SILVER_QTY: ${{ vars.PF_SILVER_QTY }}
          PF_SILVER_AVG: ${{ vars.PF_SILVER_AVG }}
          GOLD_PRICE_HIGH: ${{ vars.GOLD_PRICE_HIGH }}
          GOLD_PRICE_LOW: ${{ vars.GOLD_PRICE_LOW }}
          SILVER_PRICE_HIGH: ${{ vars.SILVER_PRICE_HIGH }}
          SILVER_PRICE_LOW: ${{ vars.SILVER_PRICE_LOW }}
          PORTFOLIO_PROFIT_THRESHOLD: ${{ vars.PORTFOLIO_PROFIT_THRESHOLD }}
          PORTFOLIO_LOSS_THRESHOLD: ${{ vars.PORTFOLIO_LOSS_THRESHOLD }}
        run: python main.py

      - name: Inject GitHub Info into HTML
        run: |
          sed -i "s/window.GH_USER = ''/window.GH_USER = '${{ github.repository_owner }}'/g" index.html
          sed -i "s/window.GH_REPO = 'charisma-monitor'/window.GH_REPO = '${{ github.event.repository.name }}'/g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4